# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 294)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 491, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setLineWidth(-1)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setLineWidth(-1)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setLineWidth(-1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setLineWidth(-1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setEnabled(True)
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setLineWidth(-1)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connectip = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.connectip.setMinimumSize(QtCore.QSize(0, 25))
        self.connectip.setBaseSize(QtCore.QSize(0, 25))
        self.connectip.setObjectName("connectip")
        self.verticalLayout_2.addWidget(self.connectip)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.apkpath = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.apkpath.setMinimumSize(QtCore.QSize(0, 25))
        self.apkpath.setBaseSize(QtCore.QSize(0, 25))
        self.apkpath.setObjectName("apkpath")
        self.horizontalLayout_2.addWidget(self.apkpath)
        self.btn_changepath = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_changepath.setObjectName("btn_changepath")
        self.horizontalLayout_2.addWidget(self.btn_changepath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.packagename = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.packagename.setMinimumSize(QtCore.QSize(0, 25))
        self.packagename.setBaseSize(QtCore.QSize(0, 25))
        self.packagename.setObjectName("packagename")
        self.verticalLayout_2.addWidget(self.packagename)
        self.startactivity = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.startactivity.setMinimumSize(QtCore.QSize(0, 25))
        self.startactivity.setBaseSize(QtCore.QSize(0, 25))
        self.startactivity.setObjectName("startactivity")
        self.verticalLayout_2.addWidget(self.startactivity)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.picpath = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.picpath.setMinimumSize(QtCore.QSize(0, 25))
        self.picpath.setBaseSize(QtCore.QSize(0, 25))
        self.picpath.setObjectName("picpath")
        self.horizontalLayout_3.addWidget(self.picpath)
        self.btn_changepath_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_changepath_2.setObjectName("btn_changepath_2")
        self.horizontalLayout_3.addWidget(self.btn_changepath_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setGeometry(QtCore.QRect(230, 240, 75, 23))
        self.btn_save.setObjectName("btn_save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.label.setText(_translate("Form", "设备IP："))
        self.label_2.setText(_translate("Form", "APK目录："))
        self.label_5.setText(_translate("Form", "应用包名："))
        self.label_6.setText(_translate("Form", "启动Activity："))
        self.label_7.setText(_translate("Form", "截图保存目录："))
        self.btn_changepath.setText(_translate("Form", "切换目录"))
        self.btn_changepath_2.setText(_translate("Form", "切换目录"))
        self.btn_save.setText(_translate("Form", "保存"))

