# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ANTool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ANTool(object):
    def setupUi(self, ANTool):
        ANTool.setObjectName("ANTool")
        ANTool.resize(687, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/oo/Desktop/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ANTool.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ANTool)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 601, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setLineWidth(-1)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setLineWidth(-1)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setLineWidth(-1)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setEnabled(True)
        self.label_10.setMinimumSize(QtCore.QSize(0, 22))
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setLineWidth(-1)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setIndent(-1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setLineWidth(-1)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setLineWidth(-1)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setLineWidth(-1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setLineWidth(-1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.connectip = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.connectip.setObjectName("connectip")
        self.horizontalLayout_6.addWidget(self.connectip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.device_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.device_2.setText("")
        self.device_2.setObjectName("device_2")
        self.gridLayout.addWidget(self.device_2, 0, 1, 1, 1)
        self.device_1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.device_1.setText("")
        self.device_1.setObjectName("device_1")
        self.gridLayout.addWidget(self.device_1, 0, 0, 1, 1)
        self.device_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.device_5.setText("")
        self.device_5.setObjectName("device_5")
        self.gridLayout.addWidget(self.device_5, 1, 1, 1, 1)
        self.device_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.device_4.setText("")
        self.device_4.setObjectName("device_4")
        self.gridLayout.addWidget(self.device_4, 1, 0, 1, 1)
        self.device_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.device_3.setText("")
        self.device_3.setObjectName("device_3")
        self.gridLayout.addWidget(self.device_3, 0, 2, 1, 1)
        self.device_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.device_6.setText("")
        self.device_6.setObjectName("device_6")
        self.gridLayout.addWidget(self.device_6, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.apkpath = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.apkpath.setObjectName("apkpath")
        self.horizontalLayout_3.addWidget(self.apkpath)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.apklist = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.apklist.setObjectName("apklist")
        self.verticalLayout_3.addWidget(self.apklist)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.overinstall = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.overinstall.setChecked(True)
        self.overinstall.setObjectName("overinstall")
        self.horizontalLayout_2.addWidget(self.overinstall)
        self.reinstall = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.reinstall.setObjectName("reinstall")
        self.horizontalLayout_2.addWidget(self.reinstall)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.packagename = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.packagename.setObjectName("packagename")
        self.verticalLayout_2.addWidget(self.packagename)
        self.startactivity = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.startactivity.setObjectName("startactivity")
        self.verticalLayout_2.addWidget(self.startactivity)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_connect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_connect.setAutoFillBackground(False)
        self.btn_connect.setObjectName("btn_connect")
        self.verticalLayout_4.addWidget(self.btn_connect)
        self.btn_getdevices = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_getdevices.setMinimumSize(QtCore.QSize(80, 23))
        self.btn_getdevices.setBaseSize(QtCore.QSize(80, 23))
        self.btn_getdevices.setObjectName("btn_getdevices")
        self.verticalLayout_4.addWidget(self.btn_getdevices)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setLineWidth(-1)
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.changepath = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.changepath.setObjectName("changepath")
        self.verticalLayout_4.addWidget(self.changepath)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setLineWidth(-1)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setLineWidth(-1)
        self.label_15.setText("")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setLineWidth(-1)
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.btn_reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout_4.addWidget(self.btn_reset)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 260, 621, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 400, 621, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 419, 601, 131))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_resultclean = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.btn_resultclean.setObjectName("btn_resultclean")
        self.horizontalLayout_4.addWidget(self.btn_resultclean)
        self.text_result = QtWidgets.QTextEdit(self.horizontalLayoutWidget_4)
        self.text_result.setObjectName("text_result")
        self.horizontalLayout_4.addWidget(self.text_result)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(40, 280, 321, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_7.setEnabled(True)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.btn_install = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.btn_install.setObjectName("btn_install")
        self.horizontalLayout_5.addWidget(self.btn_install)
        self.btn_unitstall = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.btn_unitstall.setObjectName("btn_unitstall")
        self.horizontalLayout_5.addWidget(self.btn_unitstall)
        self.btn_deviceinfo = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.btn_deviceinfo.setObjectName("btn_deviceinfo")
        self.horizontalLayout_5.addWidget(self.btn_deviceinfo)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(40, 320, 322, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.btn_screencut = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.btn_screencut.setObjectName("btn_screencut")
        self.horizontalLayout_8.addWidget(self.btn_screencut)
        self.btn_screencut_HD = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.btn_screencut_HD.setObjectName("btn_screencut_HD")
        self.horizontalLayout_8.addWidget(self.btn_screencut_HD)
        self.btn_clearcache = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.btn_clearcache.setObjectName("btn_clearcache")
        self.horizontalLayout_8.addWidget(self.btn_clearcache)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(40, 360, 427, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.btn_startapp = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn_startapp.setEnabled(False)
        self.btn_startapp.setObjectName("btn_startapp")
        self.horizontalLayout_9.addWidget(self.btn_startapp)
        self.btn_closeapp = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn_closeapp.setEnabled(False)
        self.btn_closeapp.setObjectName("btn_closeapp")
        self.horizontalLayout_9.addWidget(self.btn_closeapp)
        self.btn_closeapppid = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn_closeapppid.setEnabled(False)
        self.btn_closeapppid.setObjectName("btn_closeapppid")
        self.horizontalLayout_9.addWidget(self.btn_closeapppid)
        self.btn_getcuractivity = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn_getcuractivity.setEnabled(False)
        self.btn_getcuractivity.setObjectName("btn_getcuractivity")
        self.horizontalLayout_9.addWidget(self.btn_getcuractivity)
        ANTool.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ANTool)
        self.statusbar.setObjectName("statusbar")
        ANTool.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(ANTool)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 687, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        ANTool.setMenuBar(self.menuBar)
        self.actionSettings = QtWidgets.QAction(ANTool)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(ANTool)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbouts = QtWidgets.QAction(ANTool)
        self.actionAbouts.setObjectName("actionAbouts")
        self.menuOptions.addAction(self.actionSettings)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAbouts)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(ANTool)
        QtCore.QMetaObject.connectSlotsByName(ANTool)
        ANTool.setTabOrder(self.connectip, self.device_1)
        ANTool.setTabOrder(self.device_1, self.device_2)
        ANTool.setTabOrder(self.device_2, self.device_3)
        ANTool.setTabOrder(self.device_3, self.device_4)
        ANTool.setTabOrder(self.device_4, self.device_5)
        ANTool.setTabOrder(self.device_5, self.apkpath)
        ANTool.setTabOrder(self.apkpath, self.apklist)
        ANTool.setTabOrder(self.apklist, self.overinstall)
        ANTool.setTabOrder(self.overinstall, self.reinstall)
        ANTool.setTabOrder(self.reinstall, self.packagename)
        ANTool.setTabOrder(self.packagename, self.startactivity)
        ANTool.setTabOrder(self.startactivity, self.btn_install)
        ANTool.setTabOrder(self.btn_install, self.btn_unitstall)
        ANTool.setTabOrder(self.btn_unitstall, self.btn_deviceinfo)
        ANTool.setTabOrder(self.btn_deviceinfo, self.btn_screencut)
        ANTool.setTabOrder(self.btn_screencut, self.btn_clearcache)
        ANTool.setTabOrder(self.btn_clearcache, self.btn_startapp)
        ANTool.setTabOrder(self.btn_startapp, self.btn_closeapp)
        ANTool.setTabOrder(self.btn_closeapp, self.btn_closeapppid)
        ANTool.setTabOrder(self.btn_closeapppid, self.btn_getcuractivity)
        ANTool.setTabOrder(self.btn_getcuractivity, self.btn_resultclean)
        ANTool.setTabOrder(self.btn_resultclean, self.text_result)

    def retranslateUi(self, ANTool):
        _translate = QtCore.QCoreApplication.translate
        ANTool.setWindowTitle(_translate("ANTool", "ANTool"))
        self.label.setText(_translate("ANTool", "无线设备IP："))
        self.label_2.setText(_translate("ANTool", "设备列表："))
        self.label_10.setText(_translate("ANTool", "APK存放路径："))
        self.label_11.setText(_translate("ANTool", "APK列表："))
        self.label_4.setText(_translate("ANTool", "安装方式："))
        self.label_5.setText(_translate("ANTool", "应用包名："))
        self.label_6.setText(_translate("ANTool", "启动Activity："))
        self.overinstall.setText(_translate("ANTool", "覆盖安装"))
        self.reinstall.setText(_translate("ANTool", "卸载重装"))
        self.btn_connect.setText(_translate("ANTool", "连接无线设备"))
        self.btn_getdevices.setText(_translate("ANTool", "获取设备"))
        self.changepath.setText(_translate("ANTool", "切换目录"))
        self.label_13.setText(_translate("ANTool", "//此处不支持中文"))
        self.btn_reset.setText(_translate("ANTool", "重置以上信息"))
        self.btn_resultclean.setText(_translate("ANTool", "清空"))
        self.text_result.setHtml(_translate("ANTool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">-&gt;无线设备数据传输依赖网络情况</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">-&gt;操作开始后，需要一定的传输时间，不要着急</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">-&gt;用着用着就崩溃我也遇到过的，只能重启↖(^ω^)↗</span></p></body></html>"))
        self.label_7.setText(_translate("ANTool", "多设备操作："))
        self.btn_install.setText(_translate("ANTool", "安装"))
        self.btn_unitstall.setText(_translate("ANTool", "卸载"))
        self.btn_deviceinfo.setText(_translate("ANTool", "设备信息"))
        self.label_8.setText(_translate("ANTool", "单设备操作："))
        self.btn_screencut.setText(_translate("ANTool", "截图"))
        self.btn_screencut_HD.setText(_translate("ANTool", "HD 截图"))
        self.btn_clearcache.setText(_translate("ANTool", "清除应用缓存"))
        self.label_9.setText(_translate("ANTool", "未实现功能："))
        self.btn_startapp.setText(_translate("ANTool", "启动应用"))
        self.btn_closeapp.setText(_translate("ANTool", "关闭应用"))
        self.btn_closeapppid.setText(_translate("ANTool", "关闭进程"))
        self.btn_getcuractivity.setText(_translate("ANTool", "获取当前Activity"))
        self.menuOptions.setTitle(_translate("ANTool", "Options"))
        self.actionSettings.setText(_translate("ANTool", "Settings"))
        self.actionAbout.setText(_translate("ANTool", "About"))
        self.actionAbouts.setText(_translate("ANTool", "Abouts"))

